package com.example.latest_lottery.Data;

/**
 * Signature getter page and it is generated by GSON api extract
 *
 * @author  Pinjia Zhang
 * @version 1.0
 * @release   12/16/2021
 */

public class Sig_data {
    @com.google.gson.annotations.SerializedName("signature")
    private String signature;
    @com.google.gson.annotations.SerializedName("state_code")
    private Integer stateCode;

    public String getSignature() {
        return signature;
    }

    public void setSignature(String signature) {
        this.signature = signature;
    }

    public Integer getStateCode() {
        return stateCode;
    }

    public void setStateCode(Integer stateCode) {
        this.stateCode = stateCode;
    }
}
